# Site settings
title: Pray 4 Others
email: pray4others@lakas.network
description: The community that prays with and for each other. 
author: Team Prayer Warriors

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://pray4others.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 

google_analytics: 
addthis_id: 
disqus_account: 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/pray4othersapp
  - title: facebook
    url: https://facebook.com/pray4othersapp
  - title: instagram
    url: https://instagram.com/pray4othersapp
  - title: rss
    url: /feed.xml
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings

# Instructions from https://dzhavat.github.io/2020/01/19/adding-an-rss-feed-to-github-pages.html
plugins:
  - jekyll-feed